spring.application.name=event-booking-project

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=3600000

# File Upload Limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

brevo.api.key=${BREVO_API_KEY}

paypal.base-url=https://api-m.sandbox.paypal.com
paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_SECRET_KEY}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED}

app.cors.allowed-origins=${FRONTEND_URL}

app.currency.inr-to-usd-rate=83.5

supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}

spring.main.lazy-initialization=true

app.frontend.url=http://localhost:5173